"""empty message

Revision ID: 0f7aab28506d
Revises: 9d84378fbfe2
Create Date: 2024-02-02 21:58:00.353193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0f7aab28506d'
down_revision = '9d84378fbfe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=sqlite.JSON(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=sa.String(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
