"""empty message

Revision ID: 185ee216ae8a
Revises: ef8e4dd6b688
Create Date: 2024-02-01 01:23:34.520617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185ee216ae8a'
down_revision = 'ef8e4dd6b688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('zip_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('zip_code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
