"""empty message

Revision ID: 9d84378fbfe2
Revises: 3947f9d5fcd2
Create Date: 2024-02-02 16:20:09.926282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d84378fbfe2'
down_revision = '3947f9d5fcd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('is_open_now')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_open_now', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
